apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeidsrettet-dialog
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  liveness:
    path: arbeid/dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeid/dialog/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: arbeidsrettet-dialog/internal/metrics
  ingresses:
    - https://www.nav.no/arbeid/dialog
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester.nav.no/dittnav/'
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
