apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeidsrettet-dialog
  namespace: default
  cluster: prod-sbs
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/arbeidsrettet-dialog/arbeidsrettet-dialog:{{version}}
  port: 8080
  liveness:
    path: arbeidsrettet-dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeidsrettet-dialog/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: arbeidsrettet-dialog/internal/metrics
  ingresses:
    - https://arbeidsrettet-dialog-{{namespace}}.nais.oera-q.local
    - https://arbeidsrettet-dialog-{{namespace}}.dev-sbs.nais.io
  vault:
    enabled: true
  webproxy: true
  env:
    - APPRES_CMS_URL
    - ISSO_JWKS_URL
    - ISSO_HOST_URL
    - ISSO_ISSUER_URL
    - ISSO_ISALIVE_URL
    - VEILARBLOGIN_REDIRECT_URL_URL
    - VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    - OIDC_REDIRECT_URL
    - AAD_B2C_DISCOVERY_URL
    - VEIENTILARBEID_URL
    - AKTIVITETSPLAN_URL
    - ARBEIDSSOKERREGISTRERING_URL
    - VEILARBSTEPUP_OIDC_URL
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester-{{namespace}}.nav.no/dittnav/'
