apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeidsrettet-dialog
  namespace: {{namespace}}
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/arbeidsrettet-dialog/arbeidsrettet-dialog:{{version}}
  port: 8080
  liveness:
    path: arbeidsrettet-dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeidsrettet-dialog/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: arbeidsrettet-dialog/internal/metrics
  ingresses:
    - https://arbeidsrettet-dialog-{{namespace}}.nais.oera-q.local
    - https://arbeidsrettet-dialog-{{namespace}}.dev-sbs.nais.io
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DITTNAV_LINK_URL
      value: 'https://tjenester-{{namespace}}.nav.no/dittnav/'
  envFrom:
    - configmap: pto-config
