apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: arbeidsrettet-dialog
  namespace: pto
  labels:
    team: pto
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: arbeid/dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: arbeid/dialog/internal/selftest
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: arbeid/dialog/internal/metrics
  ingresses:
    - https://arbeidsrettet-dialog-q1.nais.oera-q.local
    - https://arbeidsrettet-dialog-q1.dev-sbs.nais.io
    - https://www-q1.nav.no/arbeid/dialog
  vault:
    enabled: true
  webproxy: true
  env:
    - name: DITTNAV_LINK_URL
      value: 'https://www.dev.nav.no/person/dittnav/'
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
