version: 2.1
orbs:
    pus: navikt/pus-orb@0.0.33

workflows:
    version: 2
    commit:
        jobs:
          - pus/bygg-frontend:
              context: pus
              name: build

          - pus/test-frontend:
                  name: test

          - pus/deploy-latest:
                requires:
                    - test
                    - build
                name: dev-sbs-deploy
                context: pus
                cluster: dev-sbs
                filepath: ./nais-q-sbs.yaml
                filters:
                  branches:
                    only: master


          - pus/deploy-latest:
                requires:
                    - test
                    - build
                name: dev-fss-deploy
                context: pus
                cluster: dev-fss
                filepath: ./nais-q-fss.yaml
                filters:
                  branches:
                    only: master