apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsrettet-dialog
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  liveness:
    path: /arbeid/dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeid/dialog/internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://pto.dev.nav.no/arbeid/dialog
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      # Chrome does not send cookie with the site.webmanifest request, dont require login for that file
      autoLoginIgnorePaths:
        - /site.webmanifest
  tokenx:
    enabled:
      true
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: arbeidsrettet-dialog-dev

  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.dev.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: CONTEXT_PATH
      value: /arbeid/dialog
    - name: JSON_CONFIG
      value: >
        {
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "gcs": { "bucketName": "arbeidsrettet-dialog-dev" },
          "auth": { "loginProvider": "ID_PORTEN" },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com"]
            }
          },
          "proxies": [
            { "fromPath": "/veilarbaktivitet", "toUrl": "http://pto-proxy/proxy/veilarbaktivitet" },
            { "fromPath": "/veilarbdialog", "toUrl": "http://pto-proxy/proxy/veilarbdialog" },
            { "fromPath": "/veilarboppfolging", "toUrl": "http://pto-proxy/proxy/veilarboppfolging" },
            { "fromPath": "/veilarblest", "toUrl": "http://pto-proxy/proxy/veilarblest" }
          ],
          "redirects": [
              {
                "fromPath": "/api/auth",
                "toUrl": "/arbeid/dialog/auth/info"
              },
              {
                "fromPath": "/aktivitetsplan",
                "toUrl": "{{AKTIVITETSPLAN_URL}}"
              },
              {
                "fromPath": "/arbeidssokerregistrering",
                "toUrl": "{{ARBEIDSSOKERREGISTRERING_URL}}"
              },
              {
                "fromPath": "/minside",
                "toUrl": "{{MINSIDE_URL}}"
              },
              {
                "fromPath": "/veientilarbeid",
                "toUrl": "{{VEIENTILARBEID_URL}}"
              }
          ]
        }
