apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsrettet-dialog-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://arbeidsrettet-dialog.intern.nav.no
  gcp:
    buckets:
      - name: arbeidsrettet-dialog-intern-prod
  envFrom:
    - configmap: pto-config
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "arbeidsrettet-dialog-intern-prod"
          },
          "cors": {
             "origin": "https://veilarbpersonflate.intern.nav.no"
           }
        }
