apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: arbeidsrettet-dialog-intern
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  liveness:
    path: /arbeid/dialog/internal/isAlive
    initialDelay: 20
  readiness:
    path: /arbeid/dialog/internal/isReady
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://arbeidsrettet-dialog.dev.intern.nav.no/arbeid/dialog
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: arbeidsrettet-dialog-intern-dev
  envFrom:
    - configmap: pto-config
  env:
    - name: CONTEXT_PATH
      value: /arbeid/dialog
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "arbeidsrettet-dialog-intern-dev"
          },
          "cors": {
             "origin": "https://veilarbpersonflate.intern.nav.no"
           }
        }
