name: Node CI

on: [push]

env:
  IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/arbeidsrettet-dialog
  TZ: Europe/Amsterdam 
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create image tag
        run: echo "::set-env name=IMAGE_TAG::$(echo ${{ github.ref }} | cut -d '/' -f3).$(date '+%F-%H%M').$(echo $GITHUB_SHA | cut -c1-7)"
      - run: npm ci
      - run: npm run test
      - run: npm run build

      - name: Build and publish Docker image
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/gh-actions'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE_NAME}:${IMAGE_TAG}
      
      - name: deply
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-fss
          RESOURCE: nais-q-fss.yaml
          VAR: namespace=q0,version=${{ IMAGE_TAG }}
