name: deploy feature branch
on:
  workflow_dispatch:

concurrency:
  group: deploy-feature-branch
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build-ekstern-dev
      bucket: arbeidsrettet-dialog-dev
      releaseName: dev-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  dev-intern:
    name: Deploy application to dev intern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build-intern-dev
      bucket: arbeidsrettet-dialog-intern-dev
      releaseName: dev-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}
