name: deploy feature branch
run-name: Deploy feature branch ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:

concurrency:
  group: deploy-feature-branch
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/dev-ekstern.yml@main
    with:
      kommando: npm run build:dev-ekstern
      bucket: arbeidsrettet-dialog-dev
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  dev-intern:
    name: Deploy application to dev intern
#    TODO @cdn -> @main før merge
    uses: navikt/arbeidsrettet-dialog/.github/workflows/deploy-intern.yml@cdn
    with:
      kommando: npm run build:dev-intern
      bucket: arbeidsrettet-dialog-dev-intern
      cdnEnv: cdn.dev.nav.no
