name: Deploy intern til CDN

on:
    workflow_call:
        inputs:
            kommando:
                required: true
                type: string
            bucket:
                required: true
                type: string
        secrets:
            SLACK_WEBHOOK:
                required: false
            READER_TOKEN:
              required: true

env:
    PRINT_PAYLOAD: true
    TZ: Europe/Amsterdam
    CI: true

jobs:
    deploy:
        name: Deploy application to CDN
        runs-on: ubuntu-latest
        permissions:
            contents: 'read'
            id-token: 'write'
            packages: 'write'
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  registry-url: "https://npm.pkg.github.com"
                  node-version: 24
                  cache: 'pnpm'
            - name: Install dependencies (pnpm)
              run: pnpm install --frozen-lockfile
              env:
                NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Run tests
              run: pnpm run test
            - name: Build application
              run: ${{ inputs.kommando }}
            - name: Upload to CDN
              uses: nais/deploy/actions/cdn-upload/v2@7ad7c2b833e1db74a80954e3ee6bb6ac060a8ae7 # master
              with:
                  team: dab
                  source: ./build/
                  destination: /${{ inputs.bucket }}/
            - name: Set special cache for asset-manifest.json
              shell: bash
              run: |
                  gcloud storage objects update gs://${BUCKET_NAME}/dab/${{ inputs.bucket }}/build/asset-manifest.json --cache-control="public, max-age=120, stale-while-revalidate=7200, stale-if-error=600"
            - name: Slack Notification (deploy failure)
              if: failure() && inputs.bucket == 'arbeidsrettet-dialog-prod-intern'
              uses: rtCamp/action-slack-notify@33ca3be66c6f378fe1610fd1d5258632dbed5e58 # v2
              env:
                  SLACK_COLOR: danger
                  SLACK_USERNAME: Github Actions
                  SLACK_ICON: https://github.com/github.png?size=48
                  SLACK_TITLE: 'Arbeidsrettet-dialog: deploy til bucket for interne brukere feilet'
                  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                  SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
