name: deploy dev og prod
on:
  push:
    branches:
      - main

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'write'

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: npm run build:dev-ekstern
      bucket: arbeidsrettet-dialog-dev-ekstern
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  dev-intern:
    name: Deploy application to dev intern
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: npm run build:dev-intern
      bucket: arbeidsrettet-dialog-dev-intern
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

  prod-ekstern:
    name: Deploy application to prod ekstern
    needs:
      - dev-ekstern
      - dev-intern
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: npm run build:prod-ekstern
      bucket: arbeidsrettet-dialog-prod-ekstern
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  prod-intern:
    name: Deploy application to prod intern
    needs: dev-intern
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: npm run build:prod-intern
      bucket: arbeidsrettet-dialog-prod-intern
      NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
