name: deploy dev og prod
on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:dev-ekstern
      bucket: arbeidsrettet-dialog-dev
      releaseName: dev-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  dev-intern:
    name: Deploy application to dev intern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:dev-intern
      bucket: arbeidsrettet-dialog-intern-dev
      releaseName: dev-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  prod-ekstern:
    name: Deploy application to prod ekstern
    needs:
      - dev-ekstern
      - dev-intern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:prod-ekstern
      bucket: arbeidsrettet-dialog-prod
      releaseName: prod-ekstern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}

  prod-intern:
    name: Deploy application to prod intern
    needs:
      - dev-ekstern
      - dev-intern
    uses: navikt/arbeidsrettet-dialog/.github/workflows/gcp-root.yml@main
    with:
      kommando: npm run build:prod-intern
      bucket: arbeidsrettet-dialog-intern-prod
      releaseName: prod-intern
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}
