name: GCP root

on:
    workflow_call:
        inputs:
            kommando:
                required: true
                type: string
            bucket:
                required: true
                type: string
        secrets:
            GCS_SA_KEY:
                required: true
            SLACK_WEBHOOK:
                required: false

env:
    PRINT_PAYLOAD: true
    TZ: Europe/Amsterdam
    CI: true

jobs:
    deploy:
        name: Deploy application to dev
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install bun
              uses: oven-sh/setup-bun@v1
            - name: Install dependencies (bun)
              run: bun install
            - name: Run tests
              run: npm run test
            - name: Build application
              run: ${{ inputs.kommando }}
            - name: Upload to CDN
              uses: nais/deploy/actions/cdn-upload/v2@master
              with:
                team: dab
                source: ./build/
                destination: /${{ inputs.bucket }}/
                no_cache_paths: ${{ inputs.bucket }}/build/index.html
                project_id: ${{ inputs.NAIS_MANAGEMENT_PROJECT_ID }}
                identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
            - name: Slack Notification (deploy failure)
              if: failure() && inputs.bucket == 'arbeidsrettet-dialog-prod'
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_COLOR: danger
                SLACK_USERNAME: Github Actions
                SLACK_ICON: https://github.com/github.png?size=48
                SLACK_TITLE: 'Arbeidsrettet-dialog: deploy til bucket for eksterne brukere feilet'
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
