name: deploy dev og prod
on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  dev-ekstern:
    name: Deploy to dev extern
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: npm run build:dev-ekstern
      bucket: arbeidsrettet-dialog-dev
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_DEV }}

  dev-intern:
    name: Deploy application to dev intern
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: npm run build:dev-intern
      bucket: arbeidsrettet-dialog-dev-intern

  prod-ekstern:
    name: Deploy application to prod ekstern
    needs:
      - dev-ekstern
      - dev-intern
    uses: ./.github/workflows/deploy-ekstern.yml
    with:
      kommando: npm run build:prod-ekstern
      bucket: arbeidsrettet-dialog-prod
    secrets:
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}

  prod-intern:
    name: Deploy application to prod intern
    needs: dev-intern
    uses: ./.github/workflows/deploy-intern.yml
    with:
      kommando: npm run build:prod-intern
      bucket: arbeidsrettet-dialog-prod-intern
