name: GCP dev

on:
  push:
    paths-ignore:
      - '.github/workflows/pto-frontend-container-dev.yml'
      - 'nais-dev-ekstern-gcp.yaml'
      - 'nais-dev-intern-gcp.yaml'
  workflow_dispatch:

concurrency:
  group: gcp_dev
  cancel-in-progress: true

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build

  deploy-ekstern-dev:
    name: Deploy ekstern dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_DEV }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://arbeidsrettet-dialog-dev
        env:
          BUCKET: gs://arbeidsrettet-dialog-dev
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/dev/dev-ekstern@${{ github.sha }}
          release_name: dev-ekstern
          prerelease: true

  deploy-intern-dev:
    name: Deploy intern dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCS_SA_KEY_DEV }}
          export_default_credentials: true
      - name: Upload files to GCS
        run: gsutil -m rsync -r build gs://arbeidsrettet-dialog-intern-dev
        env:
          BUCKET: gs://arbeidsrettet-dialog-intern-dev
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release/dev/dev-intern@${{ github.sha }}
          release_name: dev-intern
          prerelease: true
