name: Format
on: [workflow_dispatch]
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  registry-url: "https://npm.pkg.github.com"
                  node-version: 24
                  cache: 'pnpm'
            - name: Format
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run format-all
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
              with:
                  commit_user_name: Prettier bot
                  commit_author: Prettier bot <dab@nav.no>
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
