name: pto-frontend container

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pto-frontend-container.yml'
      - 'nais-dev-ekstern-gcp.yaml'
      - 'nais-dev-intern-gcp.yaml'
      - 'nais-prod-ekstern-gcp.yml'
      - 'nais-prod-intern-gcp.yml'

concurrency:
  group: pto_frontend_container
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy gcp dev intern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev-intern-gcp.yaml
      - name: deploy gcp dev ekstern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev-ekstern-gcp.yaml

  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy gcp prod ekstern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-ekstern-gcp.yaml
      - name: deploy gcp prod intern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-intern-gcp.yaml