name: pto-frontend container

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pto-frontend-container-prod.yml'
      - 'nais/nais-prod-ekstern-gcp.yml'
      - 'nais/nais-prod-intern-gcp.yml'

concurrency:
  group: pto_frontend_container_prod
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy gcp prod ekstern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-ekstern-gcp.yaml
      - name: deploy gcp prod intern
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod-intern-gcp.yaml