name: Test

on: [push, workflow_dispatch]

env:
    PRINT_PAYLOAD: true
    TZ: Europe/Amsterdam
    CI: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v7
              with:
                  registry-url: "https://npm.pkg.github.com"
                  node-version: 24
                  cache: 'pnpm'
            - name: Install dependencies (pnpm)
              run: pnpm install --frozen-lockfile
              env:
                NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - run: pnpm run test
            - run: pnpm run build
